### ISSUE TITLE
Unintended Mod Interaction between Cyclic and FTB Utilities

### ISSUE THREAD

**Issue by katubug** [FTBTeam/FTB-Utilities-Backups#12]
Minecraft Version: 
1.12.2

Forge Version: 
forge-1.12.2-14.23.5.2838-universal

Mod Version: 
- Cyclic-1.12.2-1.19.9
- FTBUtilities-5.4.0.96

Single Player or Server:
Server

Describe problem (what you were doing; what happened; what should have happened):
Okay so this is a bit weird. With FTB Utilities you can change your ingame nickname by using /nick. However, due to the way Cyclic saves its extended inventory data, this means if you /nick [something], you lose access to your extended inventory. You can /nick and it will give you access again.

However, that's not the big thing. The big thing is that if you /nick [another player's name], you can access THEIR extended inventory. It even works on players who aren't currently online.

I've also reported this to Cyclic's mod author here: https://github.com/Lothrazar/Cyclic/issues/1155

**Comment by LatvianModder** [comment]
This is Cyclic issue, it shouldn't be using display name for saving player data
