### ISSUE TITLE
Server msgs not sending correctly. 

### ISSUE THREAD

**Issue by 2iguys** [FTBTeam/FTB-Utilities-Backups#18]
![Capture](https://user-images.githubusercontent.com/9800376/64658877-f608ea00-d3ed-11e9-9537-4f6350896be1.PNG)
as it is displayed here is how it shows up ingame. 

ftbbackups.lang.(start/end) instead of showing a real message.
same thing happens when you do /backup size.

**Comment by 2iguys** [comment]
heres some more pastes.

![Capture](https://user-images.githubusercontent.com/9800376/64659204-52203e00-d3ef-11e9-93d7-84972a8b0425.PNG)
![2019-09-10_17 16 39](https://user-images.githubusercontent.com/9800376/64659213-5fd5c380-d3ef-11e9-8b2b-f5f0e961f360.png)

**Comment by 2iguys** [comment]
having a similar issue on 1.12.2, just wondering when the languages file will be written.

**Comment by ben-mkiv** [comment]
servers dont use language files, so the messages would need to be hardcoded for server side

**Comment by 2iguys** [comment]
The the question is, is there an update where that will be fixed?

**Comment by 2iguys** [comment]
might have found the issue, it has to do with the .lang file settings, I will post when I change and recompile the mod and test it

**Comment by 2iguys** [comment]
[https://i.postimg.cc/bwTzF1VM/langissue.png](url)

**Comment by 2iguys** [comment]
![langissue](https://user-images.githubusercontent.com/9800376/65850087-2fa08700-e302-11e9-92d4-0bf85b22480a.PNG)

**Comment by 2iguys** [comment]
I am a dumbass, and hadn't installed the mod both clientside and serverside, only serverside. PROBLEM SOLVED.
