### ISSUE TITLE
backups only keeping 3

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Utilities-Backups#6]
I have it set to keep 12 but it is only keeping 3

http://paste.ubuntu.com/p/t5vKKwb9Q9/

**Comment by LatvianModder** [comment]
It will delete more if there isn't enough space

**Comment by kreezxil** [comment]
There is plenty of space, I have 2 TB of hdd.

**Comment by red2blue** [comment]
lol what a useless author
